version: "2"
services:
  node:
    image: "virtual-controller:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8085"
      - "9229"
    ports: # use if it is necessary to expose the container to the host machine
      - "8085:8085"
      - "9229:9229"
    command: "node --inspect app.js"
